AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DBMasterUserName:
    Type: String
    Default: admin
    Description: Database admin user name
  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: Size of the server for the app database
  DBName:
    Type: String
    Default: cckvolunteer
    Description: App database name
  AppId:
    Type: String
    Default: cckvolunteer
    Description: App id (for resource tagging)
  Environment:
    Type: String
    Default: dev
    Description: App database name
  VPC:
    Type: String
    Default: vpc-0a7a12df50c8389a5
    Description: The VPC into which the database should be deployed

Resources:
  DBSecretKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key used to generate database access secrets
      Tags: 
        - Key: "cck:appid"
          Value: !Ref AppId
        - Key: "cck:env"
          Value: !Ref Environment
      KeyPolicy:
        Statement:
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/cloudformation-app-deployment
            Action: [
              "kms:Create*",
              "kms:Describe*",
              "kms:Enable*",
              "kms:List*",
              "kms:Put*",
              "kms:Update*",
              "kms:Revoke*",
              "kms:Disable*",
              "kms:Get*",
              "kms:Delete*",
              "kms:ScheduleKeyDeletion",
              "kms:CancelKeyDeletion",
              "kms:Decrypt",
              "kms:GenerateDataKey"
            ]
            Resource: "*"

  DBMasterSecret:
    Type: AWS::SecretsManager::Secret
    DependsOn: DBSecretKey
    Properties:
      Description: The db master user's login info
      Tags: 
        - Key: "cck:appid"
          Value: !Ref AppId
        - Key: "cck:env"
          Value: !Ref Environment
      KmsKeyId: !Ref DBSecretKey
      GenerateSecretString:
        SecretStringTemplate: !Join [ '', [ '{"username": "', !Ref DBMasterUserName, '"}' ] ]
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  DBAppSecret:
    Type: AWS::SecretsManager::Secret
    DependsOn: DBSecretKey
    Properties:
      Description: The application's database user's login info
      Tags: 
        - Key: "cck:appid"
          Value: !Ref AppId
        - Key: "cck:env"
          Value: !Ref Environment
      KmsKeyId: !Ref DBSecretKey
      GenerateSecretString:
        SecretStringTemplate: !Join [ '', [ '{"username": "', !Ref AppId, '"}' ] ]
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  DBSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Database instances security group"
      Tags: 
        - Key: "cck:appid"
          Value: !Ref AppId
        - Key: "cck:env"
          Value: !Ref Environment
      VpcId : !Ref VPC
      SecurityGroupIngress: 
        - 
          CidrIp: "0.0.0.0/0"
          FromPort: 3306
          IpProtocol: "tcp"
          ToPort: 3306
      SecurityGroupEgress: 
        - 
          CidrIp: "0.0.0.0/0"
          IpProtocol: "-1"

  DBInstance:
    Type: AWS::RDS::DBInstance
    DependsOn:
      - DBMasterSecret
      - DBSecurityGroup
    Properties:
      Tags: 
        - Key: "cck:appid"
          Value: !Ref AppId
        - Key: "cck:env"
          Value: !Ref Environment
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !Ref DBName
      Engine: "MySQL"
      VPCSecurityGroups: 
        - !Ref DBSecurityGroup
      EngineVersion: "8.0.28"
      PubliclyAccessible : True
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref DBMasterSecret, ':SecretString:password}}' ] ]
      StorageType: gp2
      StorageEncrypted: true
      AllocatedStorage: 10
      MultiAZ: False

Outputs:
  DBMasterSecretARN:
    Description: The resource id of the secret containing the db master user's login info
    Value: !Ref DBMasterSecret
  DBAppSecretARN:
    Description: The resource id of the secret containing the application's database user's login info
    Value: !Ref DBAppSecret
  DBInstanceARN:
    Description: The resource id of the launched database instance
    Value: !Ref DBInstance